# Generated by Django 4.0.4 on 2022-04-18 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0004_remove_likes_owner_likes_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='owner',
        ),
        migrations.AddField(
            model_name='likes',
            name='owner',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='like', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
